import Layout from '../../components/Layout'

const pages: Record<string, { eyebrow: string; title: string; description: string; rows: [string, string, string][] }> = {
  organizations: { eyebrow: 'ADMIN · ORGANIZATIONS', title: 'Organizations and tenant boundaries', description: 'Manage organizations, lifecycle state, quotas, and the ownership boundary for customer data.', rows: [['Organization registry', 'Tenant identity, plan and lifecycle', 'Ready for API'], ['Quota policy', 'Request, token and spend ceilings', 'Governed'], ['Data boundary', 'Isolation and residency constraints', 'Enforced']] },
  users: { eyebrow: 'ADMIN · USERS & RBAC', title: 'Users, roles, and access', description: 'Review identity state, organization membership, roles, and security posture without exposing secrets.', rows: [['Directory', 'Verified email, phone and linked providers', 'Identity'], ['Roles', 'Owner, admin, builder, viewer and support', 'RBAC'], ['Audit', 'Role changes and access decisions', 'Append-only']] },
  providers: { eyebrow: 'ADMIN · PROVIDERS', title: 'Provider health and controls', description: 'Operate provider adapters, credentials, health, circuit breakers, and failover eligibility.', rows: [['Adapter registry', 'Provider capability and configured state', 'Live'], ['Health policy', 'Timeout, retry and circuit thresholds', 'Resilience'], ['Credential boundary', 'Secret references only; never secret values', 'Protected']] },
  models: { eyebrow: 'ADMIN · MODELS & PRICING', title: 'Model catalog and pricing', description: 'Control model aliases, provider mappings, token pricing, data policies, and customer availability.', rows: [['Model catalog', 'Aliases, capabilities and context windows', 'Catalog'], ['Pricing', 'Input, output and markup rules', 'Billing'], ['Eligibility', 'Region, tier and privacy filters', 'Policy']] },
  routing: { eyebrow: 'ADMIN · ROUTING POLICY', title: 'Routing rules and fallback chains', description: 'Configure static, dynamic, policy-based, and failover routing with explainable decisions.', rows: [['Strategies', 'Static, cost, latency and quality routing', 'Router'], ['Fallbacks', 'Ordered provider/model recovery chains', 'Resilience'], ['Explainability', 'Decision reason and policy version', 'Auditable']] },
  privacy: { eyebrow: 'ADMIN · PRIVACY GOVERNANCE', title: 'Data masking and provider governance', description: 'Set classification policy, transformations, restoration permissions, and provider data-use restrictions.', rows: [['Classifications', 'PII, secrets, regulated and internal', 'Policy'], ['Transformations', 'Redact, tokenize, hash, block or encrypt', 'Privacy'], ['Retention', 'Raw, masked, metadata and export windows', 'Lifecycle']] },
}

export default function AdminSection({ section }: { section: string }) {
  const config = pages[section] || pages.organizations
  return <Layout><section className="section-hero"><div><span className="eyebrow">{config.eyebrow}</span><h2>{config.title}</h2><p>{config.description}</p></div><span className="pill">Admin control plane</span></section><section className="card table-card"><div className="table-title"><div><span className="eyebrow">CONTROL REGISTER</span><h3>Governed operating surface</h3></div><span className="pill">{config.rows.length} controls</span></div><div className="table-wrap"><table><thead><tr><th>Area</th><th>Responsibility</th><th>State</th></tr></thead><tbody>{config.rows.map(([area, detail, status]) => <tr key={area}><td><strong>{area}</strong></td><td>{detail}</td><td><span className="status-label positive">{status}</span></td></tr>)}</tbody></table></div></section><section className="dashboard-grid"><article className="card"><span className="eyebrow">SAFE DEFAULT</span><h3>No destructive controls on first render</h3><p className="muted">Administrative actions require an explicit control-plane API, role verification, audit event, and confirmation step.</p></article><article className="card"><span className="eyebrow">SOURCE OF TRUTH</span><h3>Figma-aligned governance model</h3><p className="muted">This page maps to the corresponding Admin Panel canvas frame and is ready to bind to the service contract.</p></article></section></Layout>
}

export function getStaticPaths() { return { paths: Object.keys(pages).map(section => ({ params: { section } })), fallback: false } }
export function getStaticProps({ params }: { params: { section: string } }) { return { props: { section: params.section } } }
