"""Initial Billing schema

Revision ID: 536c52156024
Revises: 
Create Date: 2026-06-17 11:00:09.567659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '536c52156024'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage_records',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('api_key_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('markup_usd', sa.Float(), nullable=False),
    sa.Column('billed_usd', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('fallback_used', sa.Boolean(), nullable=False),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('cached_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_discount_usd', sa.Float(), nullable=False),
    sa.Column('experiment_name', sa.String(length=128), nullable=True),
    sa.Column('experiment_variant', sa.String(length=64), nullable=True),
    sa.Column('schema_validation_passed', sa.Boolean(), nullable=True),
    sa.Column('validation_retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_records_api_key_id'), 'usage_records', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_usage_records_created_at'), 'usage_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_usage_records_user_id'), 'usage_records', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_records_user_id'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_created_at'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_api_key_id'), table_name='usage_records')
    op.drop_table('usage_records')
    # ### end Alembic commands ###
