import Link from 'next/link'
import NationalShell, { Eyebrow, Pager } from '../components/NationalShell'

const steps = [['01', 'Запрос', 'Данные ведомства'], ['02', 'Маскирование', 'ПДн удалены'], ['03', 'Маршрутизация', 'Лучшая модель'], ['04', 'Восстановление', 'ПДн возвращены'], ['05', 'Ответ', 'Доставлен']]
const signals = [['Стоимость', 'Политика бюджета и тариф'], ['Задержка', 'SLO и provider health'], ['Качество', 'Модельный профиль задачи'], ['Приватность', 'Классификация и eligibility']]

export default function Aggregator() {
  return <NationalShell><main className="national-page"><Eyebrow>УРОВЕНЬ 2 · СУВЕРЕННОЕ ЯДРО</Eyebrow><h1>Агрегатор — <span className="national-accent">единый защищённый шлюз</span> ко всем передовым моделям.</h1><p className="national-lede">Один OpenAI-совместимый интерфейс для провайдеров, моделей и локальных сценариев. До выхода запроса применяются маскирование ПДн, policy checks, rate limits и explainable routing.</p><section className="aggregator-hero"><div className="aggregator-card"><span className="aggregator-lock">⌁</span><div><h2>Запрос остаётся управляемым</h2><p>Клиенту не нужно знать, где и как работает модель. Платформа нормализует вход, принимает routing decision и возвращает единый ответ с usage и audit metadata.</p></div></div><div className="aggregator-card green"><span className="aggregator-lock">◌</span><div><h2>Суверенный слой данных</h2><p>Маскирование, токенизация, retention и provider eligibility остаются внутри контролируемого контура.</p></div></div></section><section className="workflow-card"><Eyebrow>DATA GOVERNANCE PIPELINE</Eyebrow><div className="workflow-steps">{steps.map(([number, title, sub], index) => <div className="workflow-step" key={number}><span>{number}</span><b>{title}</b><small>{sub}</small>{index < steps.length - 1 && <i>→</i>}</div>)}</div></section><section className="signal-grid">{signals.map(([title, text]) => <article className="signal-card" key={title}><span className="signal-mark">◈</span><h3>{title}</h3><p>{text}</p></article>)}</section><section className="routing-panel"><div><Eyebrow>ROUTE DECISION</Eyebrow><h2>Одно правило маршрутизации. Много провайдеров.</h2><p>Статический mapping, cost optimization, latency optimization, quality policies, region constraints и fallback chains работают в одном объяснимом контракте.</p></div><div className="route-list"><div><span className="route-dot green-dot" /> Navo'i LLM <small>локальный приоритет</small></div><div><span className="route-dot gold-dot" /> Qwen / Open-source <small>экономичный профиль</small></div><div><span className="route-dot blue-dot" /> Global providers <small>quality / fallback</small></div></div></section><Pager previous="02 · AI App Store" previousHref="/app-store" next="04 · Navo'i LLM" nextHref="/navoi" /></main></NationalShell>
}
