import Link from 'next/link'
import NationalShell, { Eyebrow, Pager } from '../components/NationalShell'

const apps = [
  ['g-teal', 'Документ-анализатор', 'Работа с документами', 'Разбор, извлечение и классификация документов с контролем данных.', 'Проверен'],
  ['g-brass', 'Налоговый помощник', 'Финансы и налоги', 'Подготовка ответов и поиск по утверждённым нормативным источникам.', 'Проверен'],
  ['g-navy', 'Сводка обращений', 'Государственные услуги', 'Классификация обращений и подготовка кратких резюме для операторов.', 'Проверен'],
  ['g-clay', 'Контрактный советник', 'Юстиция и закупки', 'Поиск рисков и контроль обязательных условий в контрактах.', 'На review'],
  ['g-plum', 'Отраслевой аналитик', 'Отрасли', 'Сравнение показателей, подготовка аналитических записок и сценариев.', 'Проверен'],
  ['g-slate', 'Knowledge Copilot', 'Компании', 'Корпоративный помощник с ограниченными источниками и аудитом.', 'Проверен'],
]

export default function AppStore() {
  return <NationalShell><main className="national-page"><Eyebrow>УРОВЕНЬ 1 · ДИСТРИБУЦИЯ</Eyebrow><h1>AI App Store — <span className="national-accent">рабочее пространство AI-агентов</span> для государства и бизнеса.</h1><p className="national-lede">Выбирайте проверенные агенты для конкретного сценария. Каждый пакет показывает разрешения, источники, модельный профиль, требования к данным и статус review до установки.</p><div className="national-stats store-stats"><div><b>Каталог</b><span>Готовые сценарии</span></div><div><b>Review</b><span>До публикации</span></div><div><b>RBAC</b><span>По ролям и организациям</span></div><div><b>UZS</b><span>Локальная экономика</span></div></div><section className="app-store-frame"><aside className="app-store-rail"><div className="app-store-brand"><span className="national-logo">S</span><div><strong>AI App Store</strong><small>Governed marketplace</small></div></div><Link href="/creator/register" className="national-button gold">＋ Создать агента</Link><span className="rail-label">ОБЗОР</span><span className="rail-item active">▦ Маркетплейс</span><span className="rail-item">✦ Рекомендуемые</span><span className="rail-item">✓ Проверенные</span><span className="rail-label">КАТЕГОРИИ</span><span className="rail-item">Здравоохранение</span><span className="rail-item">Финансы и налоги</span><span className="rail-item">Госуслуги</span><span className="rail-item">Компании</span></aside><div className="app-store-main"><div className="app-store-toolbar"><div className="app-search">⌕ <span>Найти AI-агента по задаче</span></div><span className="store-filter">Все категории⌄</span></div><div className="store-hero"><Eyebrow>ПЛАТФОРМА AI-АГЕНТОВ</Eyebrow><h2>Нужный AI-агент для каждого министерства, задачи и момента.</h2><p>Разворачивайте проверенные пакеты за минуты — с политиками, аудитом и требованиями к данным.</p></div><div className="store-heading"><h2>Каталог агентов</h2><span>Сортировка: рекомендованные⌄</span></div><div className="app-grid">{apps.map(([tone, title, category, text, status]) => <article className="app-card" key={title}><div className="app-card-top"><span className={`app-icon ${tone}`}>✦</span><div><h3>{title}</h3><small>{category}</small></div><span className={status === 'Проверен' ? 'verified' : 'review'}>{status}</span></div><p>{text}</p><div className="app-card-foot"><span>◈ Разрешения</span><span>◉ Аудит</span><Link href="/portal">Открыть →</Link></div></article>)}</div></div></section><Pager previous="01 · Обзор" previousHref="/" next="03 · Агрегатор" nextHref="/aggregator" /></main></NationalShell>
}
