import Link from 'next/link'
import NationalShell, { Eyebrow } from '../components/NationalShell'

const models = [
  ['g-clay', 'Claude', 'Anthropic', '✦'],
  ['g-teal', 'OpenAI', 'Семейство GPT', '◉'],
  ['g-gemini', 'Gemini', 'Google', '✦'],
  ['g-slate', 'Open-source', 'Qwen · Llama · др.', '⌗'],
]
const audiences = [
  ['aud-min', 'Министерства', 'Государственные услуги', '▦'],
  ['aud-ind', 'Отрасли', 'Сектора и госкомпании', '◈'],
  ['aud-company', 'Компании', 'Частный сектор', '□'],
]

export default function Home() {
  return <NationalShell>
    <main className="national-page national-overview">
      <section className="national-hero"><Eyebrow>Национальная AI-платформа · Республика Узбекистан</Eyebrow><h1>Единая национальная платформа.<br /><span>AI App Store</span> для каждого министерства и отрасли.</h1><p className="national-lede">Суверенная архитектура из трёх уровней: <b>AI App Store</b>, где министерства, отрасли и компании находят готовых AI-агентов; <b>Национальная платформа</b>, которая направляет каждый запрос через защищённый <b>Агрегатор</b>; и суверенная программа <b>Navo'i LLM</b> с ведущими мировыми моделями в основе.</p><div className="national-actions"><Link href="/app-store" className="national-button gold">Открыть AI App Store</Link><Link href="/aggregator" className="national-button outline">Как работает платформа</Link></div></section>
      <section className="national-architecture"><div className="national-column"><div className="national-column-label">ПЕРЕДОВЫЕ МОДЕЛИ</div>{models.map(([tone, title, sub, icon]) => <div className="national-node" key={title}><span className={`national-badge ${tone}`}>{icon}</span><div><strong>{title}</strong><small>{sub}</small></div></div>)}</div><div className="national-connectors"><span /><span /><span /><span /></div><div className="national-column core-column"><div className="national-column-label">СУВЕРЕННОЕ ЯДРО</div><div className="national-node big gold-border"><span className="national-badge g-gold">⌁</span><div><strong>Агрегатор</strong><small>Маршрутизация · маскирование ПДн · локально</small></div></div><div className="national-node big green-border"><span className="national-badge g-green">◌</span><div><strong>Navo'i LLM</strong><small>Суверенная модельная программа · локально</small></div></div></div><div className="national-connectors gold-connectors"><span /><span /></div><div className="national-column"><div className="national-column-label">НАЦИОНАЛЬНАЯ ПЛАТФОРМА</div><div className="national-node big"><span className="national-badge g-navy">⌂</span><div><strong>Национальная платформа</strong><small>Суверенные ЦОД · политики · данные</small></div></div><div className="national-node big gold-border"><span className="national-badge g-gold">▦</span><div><strong>AI App Store</strong><small>Агенты · веб · десктоп · мобильные сценарии</small></div></div></div><div className="national-connectors gold-connectors"><span /><span /><span /></div><div className="national-column audience-column"><div className="national-column-label">ПОЛЬЗОВАТЕЛИ</div>{audiences.map(([tone, title, sub, icon]) => <div className="national-node" key={title}><span className={`national-badge ${tone}`}>{icon}</span><div><strong>{title}</strong><small>{sub}</small></div></div>)}</div></section>
      <section className="national-stats"><div><b>01</b><span>Единый API</span></div><div><b>04</b><span>Ролевых портала</span></div><div><b>UZS</b><span>Локальная экономика</span></div><div><b>24/7</b><span>Контроль и аудит</span></div></section>
      <section className="national-product-grid"><Link href="/app-store" className="national-product-card"><Eyebrow>УРОВЕНЬ 1 · ДИСТРИБУЦИЯ</Eyebrow><h2>AI App Store</h2><p>Готовые проверенные агенты для министерств, отраслей и компаний. Каталог с разрешениями, review-процессом и контролируемой установкой.</p><span>02 · Перейти в App Store →</span></Link><Link href="/aggregator" className="national-product-card"><Eyebrow>УРОВЕНЬ 2 · СУВЕРЕННОЕ ЯДРО</Eyebrow><h2>Агрегатор / Router</h2><p>Единый защищённый шлюз к моделям с маршрутизацией по стоимости, задержке, качеству, приватности и доступности.</p><span>03 · Изучить маршрутизацию →</span></Link><Link href="/navoi" className="national-product-card"><Eyebrow>ПРОГРАММА РАЗВИТИЯ</Eyebrow><h2>Navo'i LLM</h2><p>Суверенная модельная программа для тюркских языков, национальных сценариев, benchmark и локального управления.</p><span>04 · Узнать о программе →</span></Link><Link href="/partnership" className="national-product-card"><Eyebrow>ЭКОСИСТЕМА</Eyebrow><h2>Партнёрство</h2><p>Модель взаимодействия для государства, отраслей, компаний, разработчиков и технологических партнёров.</p><span>05 · Стать партнёром →</span></Link></section>
      <section className="national-portal-strip"><div><Eyebrow>ПРОДУКТОВЫЕ ПОВЕРХНОСТИ</Eyebrow><h2>Одна платформа. Четыре роли.</h2><p>User Portal, Organization Admin, Platform Admin и Agent Creator работают поверх единого контроля, API и marketplace governance.</p></div><div className="national-portal-links"><Link href="/portal">User Portal</Link><Link href="/admin">Organization Admin</Link><Link href="/controller">Platform Admin</Link><Link href="/creator">Agent Creator</Link><a href="https://docs.sovable.ai" target="_blank" rel="noreferrer">Документация</a></div></section>
    </main>
  </NationalShell>
}
