import { useMemo, useState } from 'react'
import Link from 'next/link'
import Layout from '../components/Layout'

const agents = [
  { name: 'Document Copilot', category: 'Productivity', description: 'Extracts obligations, deadlines, and decisions from Uzbek, Russian, and English documents.', installs: '1.8k', status: 'Verified', tone: 'teal' },
  { name: 'Finance Analyst', category: 'Finance', description: 'Turns governed finance data into explainable reports with policy-aware masking.', installs: '946', status: 'Verified', tone: 'gold' },
  { name: 'Support Desk', category: 'Customer operations', description: 'Answers support questions using approved knowledge sources and escalation rules.', installs: '2.4k', status: 'Featured', tone: 'blue' },
  { name: 'Uzbek Translator', category: 'Language', description: 'Translates product and public-sector content while preserving terminology glossaries.', installs: '713', status: 'New', tone: 'plum' },
]

export default function CreatorPortal() {
  const [tab, setTab] = useState<'marketplace' | 'studio' | 'reviews'>('marketplace')
  const [query, setQuery] = useState('')
  const filtered = useMemo(() => agents.filter(agent => `${agent.name} ${agent.category} ${agent.description}`.toLowerCase().includes(query.toLowerCase())), [query])
  return <Layout>
    <section className="creator-hero">
      <div><span className="eyebrow">AGENT CREATOR PORTAL</span><h2>Build once. Publish a governed agent.</h2><p>Turn your expertise, workflows, and tools into installable AI applications for organizations across the Solvable marketplace.</p><div className="creator-actions"><Link href="/creator/register" className="button primary">Create creator account</Link><button className="button secondary" onClick={() => setTab('studio')}>Open creator studio</button></div></div>
      <div className="creator-hero-card"><span className="creator-orbit">S</span><strong>Creator economics</strong><b>70%+</b><small>revenue share target in UZS</small><span className="status-label positive">Review-gated publishing</span></div>
    </section>
    <nav className="creator-tabs" aria-label="Agent Creator sections"><button className={tab === 'marketplace' ? 'active' : ''} onClick={() => setTab('marketplace')}>Marketplace</button><button className={tab === 'studio' ? 'active' : ''} onClick={() => setTab('studio')}>Creator Studio</button><button className={tab === 'reviews' ? 'active' : ''} onClick={() => setTab('reviews')}>Review & releases</button></nav>
    {tab === 'marketplace' && <section className="creator-market"><div className="creator-toolbar"><div><span className="eyebrow">DISCOVERED APPLICATIONS</span><h3>Agents ready for governed installation</h3></div><input aria-label="Search agents" value={query} onChange={event => setQuery(event.target.value)} placeholder="Search agents or categories" /></div><div className="creator-grid">{filtered.map(agent => <article className="creator-card" key={agent.name}><div className={`creator-icon ${agent.tone}`}>S</div><div className="creator-card-head"><div><h4>{agent.name}</h4><span>{agent.category}</span></div><span className="creator-badge">{agent.status}</span></div><p>{agent.description}</p><div className="creator-card-foot"><span>{agent.installs} installs</span><span>UZS billing</span><button className="button secondary compact" onClick={() => setTab('reviews')}>View</button></div></article>)}</div></section>}
    {tab === 'studio' && <section className="creator-studio"><div className="creator-steps"><span className="current">01 Define</span><span>02 Permissions</span><span>03 Test</span><span>04 Submit</span></div><div className="creator-studio-grid"><article className="card"><span className="eyebrow">AGENT PACKAGE</span><h3>Describe the outcome, not the prompt</h3><p className="muted">Create a clear application contract with a purpose, input/output schema, model policy, tools, data sources, and side-effect level.</p><div className="creator-form-preview"><label>Agent name<input placeholder="e.g. Procurement Copilot" /></label><label>Primary category<select defaultValue="productivity"><option value="productivity">Productivity</option><option value="finance">Finance</option><option value="language">Language</option></select></label><label>Short description<textarea placeholder="What job does this agent help an organization complete?" /></label></div><Link href="/creator/register" className="button primary">Start a package</Link></article><article className="card"><span className="eyebrow">GOVERNANCE CHECKLIST</span><h3>Safety is part of publishing</h3><div className="creator-checks"><span>✓ Signed manifest and version</span><span>✓ Declared tool permissions</span><span>✓ Masking and retention policy</span><span>✓ Test cases and expected outputs</span><span>○ Reviewer approval before listing</span></div></article></div></section>}
    {tab === 'reviews' && <section className="creator-studio"><div className="creator-studio-grid"><article className="card"><span className="eyebrow">RELEASE PIPELINE</span><h3>From draft to trusted listing</h3><div className="creator-timeline"><div><b>Draft</b><span>Build and test privately</span></div><div><b>Automated checks</b><span>Manifest, permissions, security</span></div><div><b>Human review</b><span>Policy and quality review</span></div><div><b>Published</b><span>Installable for eligible organizations</span></div></div></article><article className="card"><span className="eyebrow">COMMERCIAL TERMS</span><h3>Transparent creator settlement</h3><p className="muted">Marketplace prices are displayed in Uzbek so&apos;m. Settlement records include gross sale, platform fee, refunds, tax metadata, and creator share. Payment activation requires a verified creator payout profile.</p><div className="creator-money"><strong>UZS</strong><span>Local currency by default</span><strong>HUMO · UZCARD · MASTERCARD</strong><span>Customer payment methods</span></div></article></div></section>}
  </Layout>
}
