apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai-routing
resources:
  - namespace.yaml
  - gateway.yaml
  - microservices.yaml
  - hpa.yaml
configMapGenerator:
  - name: routing-config
    files:
      - routing.yaml=routing.yaml
generatorOptions:
  disableNameSuffixHash: true
commonLabels:
  app.kubernetes.io/part-of: solvable-ai
  app.kubernetes.io/managed-by: kustomize
